<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Pupu.Behavior\Pupu.Behavior.csproj" />
    <ProjectReference Include="..\Pupu.Application\Pupu.Application.csproj" />
  </ItemGroup>
</Project>
